### ISSUE TITLE
Uncaught TypeError: (...).map is not a function

### ISSUE THREAD

**Issue by omidnikrah** [davguij/rxios#8]
Hi, when I replace your ajax wrapper with Rxjs Ajax, It throws me the following error:
```Uncaught TypeError: (0 , _xhrWrapper2.default)(...).map is not a function```
why?

**Comment by markfknight** [comment]
@omidnikrah You will be using a newer veriosn of RxJS than this library supports (RxJS v5). 

See [RxJS v5 to RxJS v6 breaking changes](https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/v6/migration.md), map needs to be to be piped from v6 upwards.

**Comment by omidnikrah** [comment]
Does this library not support RxJS v6?

**Comment by markfknight** [comment]
@omidnikrah No. 

There were two pull requests in to make the changes to support RxJS v6+, which have been closed by their authors due to them being out of date.

**Comment by davguij** [comment]
Sorry for so much time without any updates from my side. 

https://github.com/davguij/rxios/releases/tag/v2.0.0 should fix this.
